version: '2.0'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  flask:
    container_name: flask
    restart: always
    build: ./api
    environment:
      - FLASK_ENV=docker
      - DEFAULT_INVENTIONS_FILE_PATH=/api/data/inventions.json
    ports:
      - 5000:5000
    volumes:
      - ./api:/api
    depends_on:
      - postgres
    entrypoint: 
      - /api/init.sh

volumes:
  db-volume:
